//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICPS.Forms
{
    
    #region Windows Form Designer generated code
    public partial class AttestationsDelete
    {
        private void InitializeComponent()
        {
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            // 
            // button1
            // 
            this.button1.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button1.Text = "Удалить";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Location = new System.Drawing.Point(200, 8);
            this.button1.Name = "button1";
            this.button1.TabIndex = 0;
            this.button1.Click += new System.EventHandler(this.delete_Click);
            // 
            // button2
            // 
            this.button2.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button2.Text = "Назад";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Location = new System.Drawing.Point(200, 48);
            this.button2.Name = "button2";
            this.button2.TabIndex = 1;
            this.button2.Click += new System.EventHandler(this.exit_Click);
            // 
            // comboBox1
            // 
            this.comboBox1.BackColor = System.Drawing.SystemColors.Window;
            this.comboBox1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox1.DropDownWidth = 168;
            this.comboBox1.ForeColor = System.Drawing.SystemColors.WindowText;
            this.comboBox1.ItemHeight = 15;
            this.comboBox1.Text = "";
            this.comboBox1.Location = new System.Drawing.Point(8, 8);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(168, 21);
            this.comboBox1.TabIndex = 2;
            // 
            // AttestationsDelete
            // 
            this.ClientSize = new System.Drawing.Size(292, 86);
            this.Text = "AttestationsDelete";
            this.Controls.Add(this.button1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.comboBox1);
            this.Name = "AttestationsDelete";
            this.Load += new System.EventHandler(this.AttestationsDelete_Load);
        }
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.ComboBox comboBox1;
    }
    #endregion
}
